name: Test turms-gateway

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Set up Java
        uses: actions/setup-java@v3.13.0
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Maven Verify
        run: mvn clean verify -am -B -pl turms-gateway --no-transfer-progress