name: Verify Style

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Set up JDK
        uses: actions/setup-java@v3.13.0
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Verify Style
        run: mvn spotless:check --no-transfer-progress